PR TT
sdimkov/test-repo pull request #2
Opened 2017-03-27 00:54 UTC by sdimkov

asd

2017-03-27 00:54 UTC, sdimkov commented
PULL Comment

2017-03-28 17:07 UTC, sdimkov commented
PULL Comment 2

2018-11-13 20:30 UTC, sdimkov commented
comment

2018-11-13 20:31 UTC, sdimkov reviewed
test

2018-11-13 20:33 UTC, sdimkov reviewed
again

2018-11-13 20:37 UTC, sdimkov reviewed
aha

2018-11-13 20:57 UTC, fakeuserpz reviewed
1

2018-11-13 21:10 UTC, fakeuserpz commented
just a comment

2018-11-13 21:11 UTC, fakeuserpz requested changes
ne

2018-11-13 21:11 UTC, fakeuserpz commented on README.md
>  # TEST
nope

2018-11-13 21:11 UTC, fakeuserpz commented on README.md
> +text
a?

2018-11-13 21:35 UTC, sdimkov reviewed
ya

2018-11-13 21:43 UTC, sdimkov reviewed
test

2018-11-22 05:20 UTC, sdimkov reviewed
yes

2018-11-22 06:06 UTC, sdimkov reviewed
another review

2018-11-22 06:08 UTC, sdimkov reviewed
another

2018-11-22 06:11 UTC, sdimkov reviewed
test

2018-11-22 06:18 UTC, sdimkov reviewed
test

2018-11-22 06:21 UTC, sdimkov reviewed
a

2018-11-22 06:24 UTC, sdimkov reviewed
x

2018-11-22 06:26 UTC, sdimkov reviewed
test

2018-11-22 06:30 UTC, fakeuserpz2 requested changes
test

2018-11-27 02:28 UTC, sdimkov reviewed
test review

2020-03-30 12:59 UTC, closed without merging